CFLAGS = -g -Wall -Wextra -Werror # -DDEBUG=1

# all: image tag client
all: image client

image: image.c

# tag: tag.c

client: client.c

clean:
	rm -f *.o image client
	
# rm -f *.o image tag client
